/* =====================================================================
   題庫 B（BANK_DOC）：由 AZ104考題/ 底下的 PDF 逐題轉錄（英文原文 + 中文翻譯）

   ★ 這支檔案的主人是「文件題庫」那一位。負責題庫 A 的人請不要動這裡。
   ★ 唯一真實來源。改完跑 `python tools/build.py` 才會進 az104-practice.html。

   與題庫 A 完全獨立，切換時互不影響分數與錯題本。
   欄位同題庫 A：q/o/e 為中文，en 為 {q,o,e} 英文原文。
   n = 原始文件中的題號，方便對照 PDF。
   四種題型 mc / hs / dd / dl 的完整規格見 ../AZ900/AZ900-SPEC.md §5
   ===================================================================== */
const BANK_DOC = [
{n:1001, d:1, t:"標記與資源組織", tEn:"Tags & resource organisation",
 q:"你的公司底下有多個部門，每個部門各有若干台虛擬機器（VM）。\n公司有一個 Azure 訂用帳戶，裡面有一個名為 RG1 的資源群組，⟦所有 VM 都放在 RG1 裡⟧。\n你希望⟦把每一台 VM 與它所屬的部門關聯起來⟧。你應該怎麼做？",
 o:["為每個部門建立 Azure 管理群組（Management Group）","為每個部門建立一個資源群組","為虛擬機器指派標記（Tag）","修改虛擬機器的設定"],
 a:[2],
 e:"Azure 的資源組織由上往下有四層，每一層能做的事不同：\n・管理群組（Management Group）— 訂用帳戶之上的容器，用來把多個訂用帳戶一起套用原則與 RBAC。它管的是訂用帳戶，不是單台 VM。\n・訂用帳戶 — 計費與配額的邊界。\n・資源群組 — 資源的生命週期容器。一個資源只能屬於一個資源群組，而且資源群組之間不能巢狀。\n・標記（Tag）— 名稱／值成對的中繼資料，可以貼在訂用帳戶、資源群組、個別資源上，一個資源最多 50 個標記。標記是唯一能「橫跨」資源群組做分類的機制，也是成本分析與 Azure Policy 篩選的依據。\n本題的關鍵限制是「所有 VM 都已經在 RG1 裡」，而且題目只要求做出關聯、沒有要求搬家。既然一個資源只能屬於一個資源群組，要用資源群組分部門就得把 VM 全部搬走，成本高又不是題目要的；管理群組層級太高，碰不到單台 VM；「修改虛擬機器的設定」沒有可以填部門的欄位。所以正解是為每台 VM 指派標記，例如 Department=Sales。\n實務上再配一條 Azure Policy 強制新資源必須帶 Department 標記，就能避免有人漏貼。",
 en:{q:"Your company has serval departments. Each department has a number of virtual machines (VMs).\nThe company has an Azure subscription that contains a resource group named RG1. ⟦All VMs are located in RG1⟧.\nYou want to ⟦associate each VM with its respective department⟧. What should you do?",
     o:["Create Azure Management Groups for each department.","Create a resource group for each department.","Assign tags to the virtual machines.","Modify the settings of the virtual machines."],
     e:"Azure organises resources in four levels, each able to do different things:\n・Management group — a container above subscriptions, used to apply policy and RBAC across many subscriptions at once. It governs subscriptions, not individual VMs.\n・Subscription — the billing and quota boundary.\n・Resource group — a lifecycle container. A resource belongs to exactly one resource group, and resource groups cannot be nested.\n・Tag — a name/value pair that can be attached to subscriptions, resource groups and individual resources, up to 50 tags per resource. Tags are the only mechanism that classifies resources *across* resource group boundaries, and they are what cost analysis and Azure Policy filter on.\nThe binding constraint here is that all the VMs are already in RG1, and the question only asks for an association, not a move. Since a resource can only live in one resource group, using resource groups per department would mean relocating every VM — expensive and not what was asked. Management groups sit too high to touch a single VM, and 'modify the settings of the virtual machines' offers no field for a department. So the answer is to tag each VM, for example Department=Sales.\nIn practice, pair this with an Azure Policy that requires a Department tag on new resources so nobody forgets."}},

{n:1002, d:1, t:"條件式存取", tEn:"Conditional Access",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個 Azure Active Directory（Azure AD）訂用帳戶，你要實作一項 Azure AD 條件式存取原則。\n這項原則必須要求⟦全域管理員（Global Administrators）群組的成員，從不受信任的位置連線到 Azure AD 時，必須使用多重要素驗證（MFA）並且使用已加入 Azure AD 的裝置⟧。\n⟦解法：你進入多重要素驗證頁面去變更使用者設定⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"這一組題目考的是「同一個需求，要用哪一個介面去做」。先把兩個介面分清楚：\n・多重要素驗證頁面（每位使用者 MFA，per-user MFA）— Azure AD 的舊機制，只能把個別使用者的狀態設成停用／已啟用／已強制。它是一個「一律要求 MFA」的開關，看不到連線位置，也看不到裝置狀態，更沒有辦法要求裝置必須已加入 Azure AD。\n・條件式存取（Conditional Access）— 新機制，屬於 Azure AD Premium P1 以上。以「如果…就…」的方式運作，指派（Assignments）挑出使用者／群組、雲端應用程式、條件（位置、裝置平台、用戶端應用程式、登入風險），存取控制則分成兩塊：\n　・授權（Grant）— 允許或封鎖，允許時可以要求 MFA、要求裝置標記為合規、要求已加入混合式 Azure AD、要求核准的用戶端應用程式。\n　・工作階段（Session）— 登入頻率、持續性瀏覽器工作階段、應用程式強制的限制等，管的是登入之後的行為。\n本題的需求同時包含三件事：限定群組、限定不受信任的位置、同時要求 MFA 與已加入 Azure AD 的裝置。位置條件與裝置要求都只有條件式存取做得到，per-user MFA 頁面全部做不到，所以這個解法不達成目標。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an Azure Active Directory (Azure AD) subscription. You want to implement an Azure AD conditional access policy.\nThe policy must be configured to require members of the ⟦Global Administrators group to use Multi-Factor Authentication and an Azure AD-joined device when they connect to Azure AD from untrusted locations⟧.\n⟦Solution: You access the multi-factor authentication page to alter the user settings⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"This set of questions is about which blade can express the requirement. First, separate the two:\n・The multi-factor authentication page (per-user MFA) — the legacy Azure AD mechanism. It only sets each user's state to Disabled, Enabled or Enforced. It is an 'always require MFA' switch: it cannot see the connection location, cannot see device state, and certainly cannot demand that the device be Azure AD-joined.\n・Conditional Access — the modern mechanism, requiring Azure AD Premium P1 or above. It works as 'if… then…'. Assignments pick users/groups, cloud apps and conditions (location, device platform, client app, sign-in risk); access controls split into two:\n　・Grant — allow or block, and when allowing it can require MFA, require the device be marked compliant, require hybrid Azure AD joined, or require an approved client app.\n　・Session — sign-in frequency, persistent browser session, app-enforced restrictions: behaviour *after* sign-in.\nThe requirement here bundles three things: a specific group, an untrusted-location condition, and both MFA and an Azure AD-joined device. Location conditions and device requirements exist only in Conditional Access; the per-user MFA page can do none of them. So this solution does not meet the goal."}},

{n:1003, d:1, t:"條件式存取", tEn:"Conditional Access",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個 Azure Active Directory（Azure AD）訂用帳戶，你要實作一項 Azure AD 條件式存取原則。\n這項原則必須要求⟦全域管理員（Global Administrators）群組的成員，從不受信任的位置連線到 Azure AD 時，必須使用多重要素驗證（MFA）並且使用已加入 Azure AD 的裝置⟧。\n⟦解法：你進入 Azure 入口網站去變更該條件式存取原則的工作階段控制（session control）⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"這一題用的介面對了（條件式存取），但動到的區塊不對。條件式存取的存取控制分成兩塊，管的東西完全不同：\n・授權控制（Grant）— 決定「這次登入准不准，以及准之前要先滿足什麼」。可以選封鎖存取，或允許存取並要求下列一項以上：要求多重要素驗證、要求裝置標記為合規、要求已加入混合式 Azure AD 的裝置、要求核准的用戶端應用程式、要求應用程式保護原則、要求變更密碼。**本題的兩個要求——MFA 與已加入 Azure AD 的裝置——都在這裡。**\n・工作階段控制（Session）— 決定「登入成功之後這個工作階段怎麼受限」。包含應用程式強制的限制、Microsoft Defender for Cloud Apps 的條件式存取應用程式控制、登入頻率、持續性瀏覽器工作階段、以及自訂連續存取評估。它不能要求 MFA，也不能要求裝置狀態。\n判斷訣竅：需求裡出現「必須使用／必須是」某種驗證方式或裝置狀態，就是授權控制；出現「多久要重新登入」「瀏覽器要不要記住」「唯讀」，才是工作階段控制。\n本題要求的是驗證方式與裝置狀態，屬於授權控制，改工作階段控制達不到目標。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an Azure Active Directory (Azure AD) subscription. You want to implement an Azure AD conditional access policy.\nThe policy must be configured to require members of the ⟦Global Administrators group to use Multi-Factor Authentication and an Azure AD-joined device when they connect to Azure AD from untrusted locations⟧.\n⟦Solution: You access the Azure portal to alter the session control of the Azure AD conditional access policy⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"This time the blade is right (Conditional Access) but the wrong section is being changed. Conditional Access access controls split into two, governing quite different things:\n・Grant controls — decide 'is this sign-in allowed, and what must be satisfied first'. You can block access, or grant access and require one or more of: multi-factor authentication, device marked as compliant, hybrid Azure AD joined device, approved client app, app protection policy, password change. **Both requirements in this question — MFA and an Azure AD-joined device — live here.**\n・Session controls — decide 'once signed in, how is the session constrained'. They cover app-enforced restrictions, Conditional Access App Control via Microsoft Defender for Cloud Apps, sign-in frequency, persistent browser session and customise continuous access evaluation. They cannot require MFA and cannot require a device state.\nRule of thumb: if the requirement says a particular authentication method or device state *must* be used, it is a grant control; if it is about how often to re-authenticate, whether the browser stays signed in, or read-only access, it is a session control.\nThis question asks for an authentication method and a device state, so it is a grant control. Altering session control does not meet the goal."}},

{n:1004, d:1, t:"條件式存取", tEn:"Conditional Access",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個 Azure Active Directory（Azure AD）訂用帳戶，你要實作一項 Azure AD 條件式存取原則。\n這項原則必須要求⟦全域管理員（Global Administrators）群組的成員，從不受信任的位置連線到 Azure AD 時，必須使用多重要素驗證（MFA）並且使用已加入 Azure AD 的裝置⟧。\n⟦解法：你進入 Azure 入口網站去變更該條件式存取原則的授權控制（grant control）⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[0],
 e:"這是這一組三題裡唯一達成目標的解法。把整個原則拆開對照，就能看出每個需求各自落在哪一格：\n・指派 — 使用者和群組：選「全域管理員」這個目錄角色，對應需求裡的「全域管理員群組的成員」。\n・指派 — 雲端應用程式或動作：選 Microsoft Azure 管理（或全部雲端應用程式），對應「連線到 Azure AD」。\n・指派 — 條件：位置。先在具名位置裡把公司的可信任 IP 範圍定義成受信任位置，再把條件設成「任何位置」排除「所有受信任的位置」，就等於「不受信任的位置」。\n・存取控制 — 授權：允許存取，然後勾「要求多重要素驗證」＋「要求已加入混合式 Azure AD 的裝置」（純雲端環境則勾「要求裝置標記為合規」），並把下方選成「需要所有選取的控制項」。**這一格同時滿足了 MFA 與裝置兩個要求。**\n・存取控制 — 工作階段：本題不需要動。\n所以三個需求分別由「指派的群組」、「指派的位置條件」、「授權控制」承擔，題目提到的兩項要求都在授權控制裡，答案是「是」。\n補充：勾「需要所有選取的控制項」而不是「需要選取的控制項之一」很重要，後者會變成 MFA 或裝置任一即可，就不符合需求了。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an Azure Active Directory (Azure AD) subscription. You want to implement an Azure AD conditional access policy.\nThe policy must be configured to require members of the ⟦Global Administrators group to use Multi-Factor Authentication and an Azure AD-joined device when they connect to Azure AD from untrusted locations⟧.\n⟦Solution: You access the Azure portal to alter the grant control of the Azure AD conditional access policy⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"This is the only solution of the three that meets the goal. Break the policy apart and each requirement lands in a specific box:\n・Assignments — Users and groups: pick the Global Administrator directory role, matching 'members of the Global Administrators group'.\n・Assignments — Cloud apps or actions: pick Microsoft Azure Management (or all cloud apps), matching 'connect to Azure AD'.\n・Assignments — Conditions: Locations. Define the corporate trusted IP ranges under Named locations, then set the condition to Any location excluding All trusted locations — which is exactly 'untrusted locations'.\n・Access controls — Grant: Grant access, then tick Require multi-factor authentication plus Require hybrid Azure AD joined device (or Require device to be marked as compliant in a cloud-only estate), and set the footer to Require all the selected controls. **This one box satisfies both the MFA and the device requirement.**\n・Access controls — Session: nothing needed for this question.\nSo the three requirements are carried by the group assignment, the location condition and the grant control respectively. Both requirements named in the stem live in the grant control, so the answer is Yes.\nWorth noting: choosing 'Require all the selected controls' rather than 'Require one of the selected controls' matters — the latter would accept MFA *or* the device, which would not meet the requirement."}},

{n:1005, d:3, t:"自訂部署 cloud-init", tEn:"Custom deployment with cloud-init",
 q:"你打算把一台 ⟦Ubuntu Server⟧ 虛擬機器部署到公司的 Azure 訂用帳戶。\n你必須實作一個自訂部署，其中包含⟦加入一個特定的受信任根憑證授權單位（CA）⟧。\n你應該用下列哪一個來建立這台虛擬機器？",
 o:["New-AzureRmVm Cmdlet","New-AzVM Cmdlet","Create-AzVM Cmdlet","az vm create 命令"],
 a:[3],
 e:"要在建立 Linux VM 的同時做作業系統層的自訂（加根憑證、裝套件、寫檔案、建使用者），標準做法是 cloud-init：寫一個 cloud-init.txt，在建立 VM 時用 --custom-data 參數把它帶進去，VM 第一次開機就會執行。\n把四個選項一一對照：\n・New-AzureRmVm — Azure PowerShell 的舊模組 AzureRM，早已淘汰（2024 年 2 月起停止支援），而且它沒有帶 cloud-init 的參數。\n・New-AzVM — 現行 Az PowerShell 模組建立 VM 的 Cmdlet，本身沒有 --custom-data 這種參數。要送自訂資料得先組 Set-AzVMOperatingSystem -CustomData 或改用 ARM／Bicep 範本，不是直接一行做完。\n・Create-AzVM — 根本不存在的 Cmdlet。PowerShell 建立資源的動詞是 New-，不是 Create-，看到 Create- 開頭的 Az Cmdlet 就可以直接排除。\n・az vm create — Azure CLI 的命令，直接支援 --custom-data，把 cloud-init.txt 的完整路徑指給它即可，例如 az vm create --custom-data cloud-init.txt。\n所以正解是 az vm create。\n記法：Linux VM ＋ cloud-init ＋ 自訂初始設定 → Azure CLI 的 --custom-data。Windows 那邊對應的是自訂指令碼擴充功能（Custom Script Extension）。",
 en:{q:"You are planning to deploy an ⟦Ubuntu Server⟧ virtual machine to your company's Azure subscription.\nYou are required to implement a custom deployment that includes ⟦adding a particular trusted root certification authority (CA)⟧.\nWhich of the following should you use to create the virtual machine?",
     o:["The New-AzureRmVm cmdlet.","The New-AzVM cmdlet.","The Create-AzVM cmdlet.","The az vm create command."],
     e:"To customise the OS while creating a Linux VM (adding root certificates, installing packages, writing files, creating users), the standard route is cloud-init: write a cloud-init.txt and pass it in with the --custom-data parameter at create time, and the VM runs it on first boot.\nTaking the four options in turn:\n・New-AzureRmVm — from the legacy AzureRM PowerShell module, retired (support ended February 2024), and it has no cloud-init parameter.\n・New-AzVM — the current Az PowerShell cmdlet for creating a VM, but it has no --custom-data parameter of its own. Sending custom data means building it up via Set-AzVMOperatingSystem -CustomData or switching to an ARM/Bicep template — not one line.\n・Create-AzVM — no such cmdlet. PowerShell's verb for creating a resource is New-, not Create-; any Az cmdlet starting with Create- can be discarded on sight.\n・az vm create — the Azure CLI command, which supports --custom-data directly: just give it the full path to cloud-init.txt, e.g. az vm create --custom-data cloud-init.txt.\nSo the answer is az vm create.\nMnemonic: Linux VM + cloud-init + custom initial configuration → Azure CLI's --custom-data. The Windows equivalent is the Custom Script Extension."}},

{n:1006, d:1, t:"MFA 提供者使用模型", tEn:"MFA provider usage model",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司在使用者不在辦公室時會使用多重要素驗證（MFA），使用模型（usage model）設定為⟦每次驗證計費（Per Authentication）⟧。\n公司併購了一家較小的企業，並把新員工加進 Azure Active Directory（Azure AD），你被告知這些員工也要使用 MFA。\n為此，使用模型必須改成⟦每位已啟用的使用者計費（Per Enabled User）⟧。\n⟦解法：你透過 Azure 入口網站重新設定現有的使用模型⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"Azure MFA 提供者（Multi-Factor Authentication Provider）有兩種使用模型，也就是兩種計費方式：\n・每位已啟用的使用者（Per Enabled User）— 按「啟用了 MFA 的使用者人數」計費，不管每個人驗證幾次。適合人數少、但每人驗證次數多的情況。\n・每次驗證（Per Authentication）— 按「驗證的總次數」計費，不管有多少人。適合人數多、但每人偶爾才驗證一次的情況（例如只有外部登入才要 MFA）。\n關鍵限制：**使用模型是在建立提供者時決定的，建立之後不能更改。** 這是這一組題目的考點，不管你用哪個介面都一樣改不了：\n・Azure 入口網站 — 提供者的使用模型欄位是唯讀的（本題）。\n・Azure CLI／PowerShell — 沒有對應的命令。\n所以唯一的做法是建立一個新的 MFA 提供者、選好想要的使用模型，再用新提供者的啟用認證重新啟用現有的 MFA 伺服器。\n因此透過入口網站重新設定現有使用模型無法達成目標，答案是「否」。\n附帶一提：這一組題目談的是舊的 MFA 提供者模型。現行做法是 Azure AD Premium P1／P2 授權直接包含 MFA，不再需要另外建立 MFA 提供者，只有 2018 年 9 月以前建立的提供者還留著。考試仍然會考這個限制。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company makes use of Multi-Factor Authentication for when users are not in the office. The ⟦Per Authentication⟧ option has been configured as the usage model.\nAfter the acquisition of a smaller business and the addition of the new staff to Azure Active Directory (Azure AD), you are informed that these employees should also make use of Multi-Factor Authentication.\nTo achieve this, the ⟦Per Enabled User⟧ setting must be set for the usage model.\n⟦Solution: You reconfigure the existing usage model via the Azure portal⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"An Azure Multi-Factor Authentication Provider has two usage models, which are really two billing models:\n・Per Enabled User — billed on the number of users enabled for MFA, regardless of how often each authenticates. Suits few users authenticating often.\n・Per Authentication — billed on the total number of authentications, regardless of how many users. Suits many users authenticating only occasionally (for example, MFA only on external sign-ins).\nThe binding constraint: **the usage model is chosen when the provider is created and cannot be changed afterwards.** That is the point of this question set, and it holds whichever interface you reach for:\n・Azure portal — the provider's usage model field is read-only (this question).\n・Azure CLI / PowerShell — there is no command for it.\nSo the only way is to create a new MFA provider with the desired usage model, then re-activate the existing MFA server using activation credentials from the new provider.\nReconfiguring the existing usage model via the portal therefore does not meet the goal: the answer is No.\nAside: this question set concerns the legacy MFA provider model. Today an Azure AD Premium P1/P2 licence includes MFA outright and no separate provider is needed; only providers created before September 2018 still exist. The exam still tests this restriction."}},

{n:1007, d:1, t:"MFA 提供者使用模型", tEn:"MFA provider usage model",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司在使用者不在辦公室時會使用多重要素驗證（MFA），使用模型（usage model）設定為⟦每次驗證計費（Per Authentication）⟧。\n公司併購了一家較小的企業，並把新員工加進 Azure Active Directory（Azure AD），你被告知這些員工也要使用 MFA。\n為此，使用模型必須改成⟦每位已啟用的使用者計費（Per Enabled User）⟧。\n⟦解法：你透過 Azure CLI 重新設定現有的使用模型⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"這一題與前一題是同一個考點，只是把介面從 Azure 入口網站換成 Azure CLI。\n先重述限制：**MFA 提供者的使用模型在建立時就固定了，之後任何介面都改不了。** 所以換介面完全無濟於事：\n・Azure 入口網站 — 使用模型欄位唯讀。\n・Azure CLI — 沒有任何 az 命令可以改 MFA 提供者的使用模型。az ad 底下管的是 Azure AD 的目錄物件，MFA 提供者的計費模型不在其中。\n・Azure PowerShell — 同樣沒有對應的 Cmdlet。\n・重新設定 MFA 伺服器 — 那是本地端元件，改不到雲端提供者的計費模型。\n唯一可行的路是：建立一個新的 MFA 提供者、在建立時選「每位已啟用的使用者」，然後用新提供者的啟用認證重新啟用現有的 MFA 伺服器。\n答案是「否」。\n作答訣竅：這一整組題目只要看到「重新設定既有提供者的使用模型」，不管後面接的是入口網站、CLI、PowerShell，一律是「否」；只有「建立新的提供者」那條路才可能是「是」。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company's Azure solution makes use of Multi-Factor Authentication for when users are not in the office. The ⟦Per Authentication⟧ option has been configured as the usage model.\nAfter the acquisition of a smaller business and the addition of the new staff to Azure Active Directory (Azure AD), you are informed that these employees should also make use of Multi-Factor Authentication.\nTo achieve this, the ⟦Per Enabled User⟧ setting must be set for the usage model.\n⟦Solution: You reconfigure the existing usage model via the Azure CLI⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"Same point as the previous question, with the interface swapped from the Azure portal to the Azure CLI.\nRestating the constraint: **an MFA provider's usage model is fixed at creation and cannot be changed afterwards, through any interface.** Changing tools achieves nothing:\n・Azure portal — the usage model field is read-only.\n・Azure CLI — no az command changes an MFA provider's usage model. The az ad commands manage Azure AD directory objects; an MFA provider's billing model is not among them.\n・Azure PowerShell — likewise no cmdlet for it.\n・Reconfiguring the MFA Server — that is the on-premises component and cannot reach the cloud provider's billing model.\nThe only workable route is to create a new MFA provider, choosing Per Enabled User at creation time, then re-activate the existing MFA Server with activation credentials from the new provider.\nThe answer is No.\nExam tip: throughout this set, any solution that reconfigures the usage model of the *existing* provider is No — portal, CLI or PowerShell alike. Only creating a *new* provider can possibly be Yes."}},

{n:1008, d:1, t:"MFA 提供者使用模型", tEn:"MFA provider usage model",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司在使用者不在辦公室時會使用多重要素驗證（MFA），使用模型（usage model）設定為⟦每次驗證計費（Per Authentication）⟧。\n公司併購了一家較小的企業，並把新員工加進 Azure Active Directory（Azure AD），你被告知這些員工也要使用 MFA。\n為此，使用模型必須改成⟦每位已啟用的使用者計費（Per Enabled User）⟧。\n⟦解法：你用現有多重要素驗證提供者資料的備份，建立一個新的多重要素驗證提供者⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"先把這一組題目的限制講完整：**MFA 提供者的使用模型在建立時決定，之後改不了。** 想換模型，官方文件給的唯一路徑是三步：\n1. 建立一個新的 MFA 提供者，建立時選好要的使用模型（本題要「每位已啟用的使用者」）。\n2. 如果原本有本地端的 MFA 伺服器，從舊提供者匯出（備份）使用者資料，匯入新提供者。\n3. 用新提供者的啟用認證，重新啟用現有的 MFA 伺服器。\n本題的解法涵蓋了第 1 步與第 2 步。\n⚠️ **注意：原始文件把本題標為「否」，但這個標記在社群有明顯爭議。** 原始文件自己附的說明就寫「由於目前無法變更既有提供者的使用模型，你必須建立一個新的，並用新提供者的啟用認證重新啟用現有的伺服器」——那正是本題解法在做的事。多數社群答案認為本題應為「是」，因為它是這一組三題裡唯一走對路的解法（前兩題都是想改既有提供者）。\n若真要替「否」找理由，只能說解法沒有明講第 3 步「用新的啟用認證重新啟用 MFA 伺服器」，所以嚴格說還沒完成切換。這個理由相當牽強。\n本題依規定照原始文件的標記轉錄為「否」，但**實際考試遇到同樣敘述時，答「是」的把握比較大**。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company's Azure solution makes use of Multi-Factor Authentication for when users are not in the office. The ⟦Per Authentication⟧ option has been configured as the usage model.\nAfter the acquisition of a smaller business and the addition of the new staff to Azure Active Directory (Azure AD), you are informed that these employees should also make use of Multi-Factor Authentication.\nTo achieve this, the ⟦Per Enabled User⟧ setting must be set for the usage model.\n⟦Solution: You create a new Multi-Factor Authentication provider with a backup from the existing Multi-Factor Authentication provider data⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"First, the constraint in full: **an MFA provider's usage model is decided at creation and cannot be changed later.** To switch models, the documented route has three steps:\n1. Create a new MFA provider, selecting the desired usage model at creation (here, Per Enabled User).\n2. If an on-premises MFA Server exists, export (back up) the user data from the old provider and import it into the new one.\n3. Re-activate the existing MFA Server using activation credentials from the new provider.\nThis question's solution covers steps 1 and 2.\n⚠️ **Note: the source document marks this as No, but that marking is clearly disputed in the community.** The document's own explanatory note says 'since it is not possible to change the usage model of an existing provider, you have to create a new one and reactivate your existing server with activation credentials from the new provider' — which is precisely what this solution does. Most community answers hold that this should be Yes, since it is the only solution in the set that takes the right route (the other two try to change the existing provider).\nThe only defence of No is that the solution never states step 3, re-activating the MFA Server with the new activation credentials, so strictly the migration is unfinished. That reasoning is thin.\nThis entry transcribes the source marking (No) as required, but **if the same wording appears in the real exam, Yes is the safer answer**."}},

{n:1009, d:1, t:"Azure AD Connect 同步", tEn:"Azure AD Connect sync",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個名為 weyland.com 的 Azure Active Directory（Azure AD）租用戶，並與本地端 Active Directory 網域設定為混合式共存。\n你有一台名為 DirSync1 的伺服器，設定為 DirSync 伺服器。\n你在本地端 Active Directory 建立了一個新的使用者帳戶，現在需要⟦立刻⟧把這個使用者資訊複寫到 Azure AD。\n⟦解法：你執行 Start-ADSyncSyncCycle -PolicyType Initial 這個 PowerShell Cmdlet⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"手動觸發 Azure AD Connect 同步的 Cmdlet 是 Start-ADSyncSyncCycle，它有兩種 -PolicyType：\n・Delta（差異同步）— 只處理上次同步之後有變動的物件。這是排程每 30 分鐘自動跑的類型，也是「剛改了一筆資料、想立刻推上去」該用的。通常幾秒到一兩分鐘就好。\n・Initial（初始／完整同步）— 把整個目錄重新完整匯入並重新評估所有同步規則。用在改了同步規則、換了篩選範圍、加了新的屬性對應之後。大型目錄可能跑好幾個小時。\n本題只是新增了一個使用者帳戶，要的是「立刻」複寫這一筆變更，正確的做法是 Start-ADSyncSyncCycle -PolicyType Delta。用 Initial 雖然最後也會把這個使用者同步過去，但它做的是全量重新匯入，與題目要求的「立刻」相違背，在正式環境還可能造成長時間的負載。\n所以答案是「否」。\n順帶釐清名詞：題目說「DirSync 伺服器」，DirSync 是最早的目錄同步工具，之後演進為 Azure AD Sync，再到現在的 Azure AD Connect（現稱 Microsoft Entra Connect）。Start-ADSyncSyncCycle 屬於 Azure AD Connect 的 ADSync 模組；真正的舊版 DirSync 用的是 Start-OnlineCoexistenceSync。考題習慣混用這些名稱，看到就當成 Azure AD Connect。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an Azure Active Directory (Azure AD) tenant named weyland.com that is configured for hybrid coexistence with the on-premises Active Directory domain.\nYou have a server named DirSync1 that is configured as a DirSync server.\nYou create a new user account in the on-premise Active Directory. You now need to replicate the user information to Azure AD ⟦immediately⟧.\n⟦Solution: You run the Start-ADSyncSyncCycle -PolicyType Initial PowerShell cmdlet⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"The cmdlet that manually triggers an Azure AD Connect sync is Start-ADSyncSyncCycle, and it takes two -PolicyType values:\n・Delta — processes only objects changed since the last sync. This is what the built-in 30-minute schedule runs, and what you want when you have just changed something and need it pushed now. Usually seconds to a couple of minutes.\n・Initial — a full re-import of the whole directory with all sync rules re-evaluated. Used after changing sync rules, altering filtering scope, or adding attribute mappings. On a large directory it can run for hours.\nHere a single user account was added and the requirement is to replicate that one change immediately, so the correct call is Start-ADSyncSyncCycle -PolicyType Delta. Initial would eventually sync the user too, but it performs a full re-import, which contradicts 'immediately' and can load a production server for a long time.\nSo the answer is No.\nA note on names: the stem says 'DirSync server'. DirSync was the original directory sync tool, which became Azure AD Sync and then today's Azure AD Connect (now Microsoft Entra Connect). Start-ADSyncSyncCycle belongs to Azure AD Connect's ADSync module; genuine legacy DirSync used Start-OnlineCoexistenceSync. Exam questions mix these names freely — read them as Azure AD Connect."}},

{n:1010, d:1, t:"Azure AD Connect 同步", tEn:"Azure AD Connect sync",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個名為 weyland.com 的 Azure Active Directory（Azure AD）租用戶，並與本地端 Active Directory 網域設定為混合式共存。\n你有一台名為 DirSync1 的伺服器，設定為 DirSync 伺服器。\n你在本地端 Active Directory 建立了一個新的使用者帳戶，現在需要⟦立刻⟧把這個使用者資訊複寫到 Azure AD。\n⟦解法：你使用「Active Directory 站台及服務」強制在某台網域控制站上複寫全域編錄（Global Catalog）⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"這一題的關鍵是分清楚兩種完全不同的「複寫」：\n・本地端 AD 網域控制站之間的複寫 — 由 Active Directory 站台及服務（Active Directory Sites and Services）管理，走 AD 自己的複寫拓撲，把變更從一台 DC 傳到另一台 DC，包含全域編錄的複寫。它的範圍完全在本地端網域內。\n・本地端 AD 到 Azure AD 的同步 — 由 Azure AD Connect（舊稱 DirSync／Azure AD Sync）負責，預設每 30 分鐘跑一次差異同步，也可以用 Start-ADSyncSyncCycle -PolicyType Delta 手動觸發。這是唯一能把物件送上雲端的路徑。\n本題要的是把新使用者送到 Azure AD，屬於第二種。用站台及服務強制全域編錄複寫，只會讓這個新使用者更快出現在其他本地端 DC 上，對 Azure AD 一點作用都沒有——Azure AD Connect 仍然要等到下一次同步週期才會抓到。\n所以答案是「否」。\n附帶一提：這個動作在真實情境裡並非全無意義。如果 Azure AD Connect 伺服器連的那台 DC 還沒收到變更，強制複寫可以確保下一次同步抓得到；但它本身不會觸發同步，達不到「立刻複寫到 Azure AD」的要求。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an Azure Active Directory (Azure AD) tenant named weyland.com that is configured for hybrid coexistence with the on-premises Active Directory domain.\nYou have a server named DirSync1 that is configured as a DirSync server.\nYou create a new user account in the on-premise Active Directory. You now need to replicate the user information to Azure AD ⟦immediately⟧.\n⟦Solution: You use Active Directory Sites and Services to force replication of the Global Catalog on a domain controller⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"The point here is to separate two quite different kinds of replication:\n・Replication between on-premises AD domain controllers — managed by Active Directory Sites and Services, following AD's own replication topology to carry changes from one DC to another, including Global Catalog replication. Its scope is entirely within the on-premises domain.\n・Synchronisation from on-premises AD to Azure AD — handled by Azure AD Connect (formerly DirSync / Azure AD Sync), running a delta sync every 30 minutes by default, or on demand via Start-ADSyncSyncCycle -PolicyType Delta. This is the only path that puts objects in the cloud.\nThe requirement is to get the new user into Azure AD, which is the second kind. Forcing Global Catalog replication with Sites and Services only makes the new user appear sooner on other on-premises DCs; it does nothing for Azure AD, which still waits for Azure AD Connect's next sync cycle.\nSo the answer is No.\nAside: the action is not entirely pointless in real life. If the DC that the Azure AD Connect server talks to has not received the change yet, forcing replication makes sure the next sync picks it up — but it does not trigger a sync itself, so it cannot satisfy 'replicate to Azure AD immediately'."}},

{n:1011, d:1, t:"Azure AD Connect 同步", tEn:"Azure AD Connect sync",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個名為 weyland.com 的 Azure Active Directory（Azure AD）租用戶，並與本地端 Active Directory 網域設定為混合式共存。\n你有一台名為 DirSync1 的伺服器，設定為 DirSync 伺服器。\n你在本地端 Active Directory 建立了一個新的使用者帳戶，現在需要⟦立刻⟧把這個使用者資訊複寫到 Azure AD。\n⟦解法：你在某台網域控制站上重新啟動 NetLogon 服務⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"NetLogon（Net Logon）服務負責的是：為使用者與服務向網域控制站做驗證的安全通道、DC 定位（在 DNS 註冊 SRV 記錄）、以及電腦帳戶的密碼變更。它跟目錄同步沒有任何關係。\n把這一組三題的三個解法一起對照，就能看出考點：\n・Start-ADSyncSyncCycle -PolicyType Initial — 工具對了（Azure AD Connect），但類型錯了，要的是 Delta。\n・Active Directory 站台及服務強制複寫全域編錄 — 管的是本地端 DC 之間的複寫，碰不到 Azure AD。\n・重新啟動 NetLogon 服務（本題）— 管的是驗證通道與 DC 定位，跟同步完全無關；重啟它反而可能讓該台 DC 短時間內無法處理驗證要求。\n三個都達不到「立刻把新使用者複寫到 Azure AD」。唯一正確的做法是在 Azure AD Connect 伺服器上執行：\nImport-Module ADSync\nStart-ADSyncSyncCycle -PolicyType Delta\n所以答案是「否」。\n記法：只要解法沒有動到 Azure AD Connect／ADSync，就不可能把資料推上 Azure AD。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an Azure Active Directory (Azure AD) tenant named weyland.com that is configured for hybrid coexistence with the on-premises Active Directory domain.\nYou have a server named DirSync1 that is configured as a DirSync server.\nYou create a new user account in the on-premise Active Directory. You now need to replicate the user information to Azure AD ⟦immediately⟧.\n⟦Solution: You restart the NetLogon service on a domain controller⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"The Net Logon service is responsible for the secure channel used to authenticate users and services against domain controllers, for DC locator (registering SRV records in DNS), and for computer account password changes. It has nothing to do with directory synchronisation.\nLining up all three solutions in this set shows what is being tested:\n・Start-ADSyncSyncCycle -PolicyType Initial — right tool (Azure AD Connect), wrong policy type; Delta is what is needed.\n・Forcing Global Catalog replication in Active Directory Sites and Services — governs replication between on-premises DCs and cannot reach Azure AD.\n・Restarting the NetLogon service (this question) — governs the authentication channel and DC locator, entirely unrelated to sync; restarting it may even leave that DC briefly unable to service authentication requests.\nNone of the three replicates the new user to Azure AD immediately. The one correct approach is to run, on the Azure AD Connect server:\nImport-Module ADSync\nStart-ADSyncSyncCycle -PolicyType Delta\nSo the answer is No.\nMnemonic: if a solution does not touch Azure AD Connect / ADSync, it cannot push anything to Azure AD."}},

{n:1012, d:2, t:"儲存體備援", tEn:"Storage redundancy",
 q:"你的公司有一個 Microsoft Azure 訂用帳戶，並在洛杉磯與紐約各有一座資料中心。\n你正把這兩座資料中心設定為異地叢集站台，以提供站台層級的復原能力，並需要建議一個 Azure 儲存體備援選項。\n你有下列資料儲存需求：\n・資料必須存放在多個節點上。\n・資料必須存放在分處不同地理位置的節點上。\n・⟦除了主要位置之外，也必須能夠從次要位置讀取資料⟧。\n你應該建議下列哪一個 Azure 儲存體備援選項？",
 o:["異地備援儲存體（Geo-redundant storage，GRS）","唯讀異地備援儲存體（Read-only geo-redundant storage，RA-GRS）","區域備援儲存體（Zone-redundant storage，ZRS）","本機備援儲存體（Locally redundant storage，LRS）"],
 a:[1],
 e:"Azure 儲存體備援選項，由弱到強：\n・LRS 本機備援 — 同一座資料中心內 3 份複本。只防硬碟或機架故障，年持久性 11 個 9。\n・ZRS 區域備援 — 同一區域的 3 個可用性區域各 1 份。可防單一資料中心失效，但不跨區域，年持久性 12 個 9。\n・GRS 異地備援 — 主要區域先做 LRS 3 份，再非同步複寫到數百公里外的配對區域，該區域再存 3 份。**次要複本平時完全無法存取**，要等 Microsoft 起始容錯移轉（或自己執行帳戶容錯移轉）才能用。年持久性 16 個 9。\n・RA-GRS 讀取權限異地備援 — GRS 再加一個永久可用的次要唯讀端點（帳戶名稱後面加 -secondary），隨時可讀。\n・GZRS 異地區域備援 — 主要區域用 ZRS（跨 3 個可用性區域），再複寫到配對區域做 LRS。區域內與跨區域都有保障。\n・RA-GZRS — GZRS 且次要可讀，備援等級最高。\n把本題三個需求逐一套進去：「多個節點」四個選項都滿足；「不同地理位置」排除 LRS 與 ZRS（兩者都在同一個區域內）；「次要位置也要能讀」排除 GRS（次要平時讀不到）。剩下 RA-GRS，正解是選項 B。\n判斷訣竅：看到「read from the secondary／次要位置也要能讀」，就一定是 RA- 開頭那兩個（RA-GRS 或 RA-GZRS）；只寫「異地備援」而沒提到讀取，才是 GRS。",
 en:{q:"Your company has a Microsoft Azure subscription. The company has datacenters in Los Angeles and New York.\nYou are configuring the two datacenters as geo-clustered sites for site resiliency. You need to recommend an Azure storage redundancy option.\nYou have the following data storage requirements:\n・Data must be stored on multiple nodes.\n・Data must be stored on nodes in separate geographic locations.\n・⟦Data can be read from the secondary location as well as from the primary location⟧.\nWhich of the following Azure stored redundancy options should you recommend?",
     o:["Geo-redundant storage (GRS)","Read-only geo-redundant storage (RA-GRS)","Zone-redundant storage (ZRS)","Locally redundant storage (LRS)"],
     e:"Azure Storage redundancy options, weakest to strongest:\n・LRS, locally redundant — 3 copies inside a single datacenter. Protects against disk or rack failure only; eleven 9s of annual durability.\n・ZRS, zone-redundant — 1 copy in each of 3 availability zones in the same region. Survives the loss of one datacenter but does not cross regions; twelve 9s.\n・GRS, geo-redundant — LRS (3 copies) in the primary region, then asynchronous replication to a paired region hundreds of kilometres away, where another 3 copies are held. **The secondary copy is completely inaccessible in normal operation** — it becomes usable only after Microsoft initiates a failover, or you perform an account failover yourself. Sixteen 9s.\n・RA-GRS, read-access geo-redundant — GRS plus a permanently available read-only secondary endpoint (account name suffixed with -secondary), readable at any time.\n・GZRS, geo-zone-redundant — ZRS in the primary region (across 3 availability zones), replicated to the paired region as LRS. Covers both in-region and cross-region failure.\n・RA-GZRS — GZRS with a readable secondary; the highest level of redundancy.\nApplying the three requirements: 'multiple nodes' is met by all four; 'separate geographic locations' eliminates LRS and ZRS, since both stay within one region; 'read from the secondary' eliminates GRS, whose secondary cannot normally be read. RA-GRS is what remains, so the answer is option B.\nRule of thumb: whenever a stem says the secondary must be readable, it is one of the RA- options (RA-GRS or RA-GZRS); plain 'geo-redundant' with no mention of reading is GRS."}},

{n:1013, d:1, t:"檢視 ARM 範本", tEn:"Reviewing an ARM template",
 q:"注意：本題與另外數題的情境完全相同，但每一題提出的解法不同，請個別判斷解法是否達成目標。\n你的公司有一個 Azure 訂用帳戶，裡面包含一個儲存體帳戶、一個資源群組、一個 Blob 容器和一個檔案共用。\n一位名叫 Jon Ross 的同事⟦用單一個 Azure Resource Manager（ARM）範本⟧部署了一台虛擬機器和一個額外的 Azure 儲存體帳戶。\n你想要⟦檢視 Jon Ross 所使用的那個 ARM 範本⟧。\n⟦解法：你進入「虛擬機器」刀鋒⟧。這個解法是否達成目標？",
 o:["是","否"],
 a:[1],
 e:"要找「某次部署實際用了哪一份 ARM 範本」，看的是**部署歷程記錄**，而部署歷程記錄掛在資源群組上，不在個別資源上。\n正確路徑：資源群組 → 選 RG → 左側「部署（Deployments）」→ 挑那一次部署 → 「範本（Template）」，就能看到當次的 template.json 與 parameters.json，還可以直接下載。\n為什麼不是「虛擬機器」刀鋒：\n・VM 刀鋒的「匯出範本（Export template）」給的是**依現況重新產生**的範本，不是 Jon Ross 當初用的那一份。兩者常常不一樣——匯出的範本會帶上部署後才有的屬性、失去原本的參數與變數、也不會包含同一份範本裡其他資源。\n・更關鍵的是本題的範本一次部署了「一台 VM ＋一個儲存體帳戶」兩種資源。從 VM 刀鋒匯出只會拿到 VM 那一段，看不到儲存體帳戶，等於看不到原本的範本。\n・資源群組層級的部署歷程記錄則是 Azure 保存的當次部署原件（每個資源群組保留最近 800 次部署），才是題目要的東西。\n所以答案是「否」，應該去資源群組刀鋒。\n記法：「這次部署用了什麼範本」→ 資源群組的部署歷程記錄；「把現在的樣子變成範本」→ 資源或資源群組的匯出範本。兩者用途不同，考題很愛拿來互換。",
 en:{q:"Note: The question is included in a number of questions that depicts the identical set-up. However, every question has a distinctive result. Establish if the solution satisfies the requirements.\nYour company has an azure subscription that includes a storage account, a resource group, a blob container and a file share.\nA colleague named Jon Ross makes use of a ⟦solitary Azure Resource Manager (ARM) template⟧ to deploy a virtual machine and an additional Azure Storage account.\nYou want to ⟦review the ARM template that was used by Jon Ross⟧.\n⟦Solution: You access the Virtual Machine blade⟧. Does the solution meet the goal?",
     o:["Yes","No"],
     e:"To find which ARM template a particular deployment actually used, you look at the **deployment history**, and deployment history hangs off the resource group, not off individual resources.\nThe correct path: Resource groups → select RG → Deployments in the left menu → pick that deployment → Template, which shows the template.json and parameters.json used at the time and lets you download them.\nWhy not the Virtual Machine blade:\n・The VM blade's Export template produces a template **regenerated from the current state**, not the one Jon Ross used. The two routinely differ — an exported template carries properties that only exist post-deployment, loses the original parameters and variables, and omits other resources that were in the same template.\n・More decisively, the template here deployed two kinds of resource at once: a VM and a storage account. Exporting from the VM blade yields only the VM portion, with no sign of the storage account — so it is not the original template.\n・Deployment history at the resource group level, by contrast, is Azure's stored record of that deployment (the last 800 deployments are kept per resource group), which is exactly what the question asks for.\nSo the answer is No; the Resource group blade is the right place.\nMnemonic: 'what template did this deployment use' → resource group deployment history; 'turn the current state into a template' → Export template on a resource or resource group. Exam questions love swapping the two."}}
];
